[package]
name = "uiuifree-crawl-cache"
version = "0.1.3"
edition = "2021"
authors = ["uiuifree"]
description = "Crawl Cache"
license = "MIT"
[dependencies]
reqwest = "0.12"
tokio = { version = "1", features = ["full"] }